// <auto-generated />
using HackerBank.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HackerBank.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328052514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HackerBank.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Balance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1985.40m,
                            Balance = "$12,234.45",
                            Date = "2019-12-03",
                            Description = "HACKERBANK INC. DES:CCD+ ID: 33375894749",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 500.00m,
                            Balance = "$12,734.45",
                            Date = "2019-12-03",
                            Description = "TRANSFER FROM SAVINGS DES:TRANSFER ID: 77291038471",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 134.56m,
                            Balance = "$12,599.89",
                            Date = "2019-12-04",
                            Description = "WALMART SUPERCENTER #4281 PURCHASE",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 12.99m,
                            Balance = "$12,586.90",
                            Date = "2019-12-04",
                            Description = "NETFLIX.COM SUBSCRIPTION",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 3200.00m,
                            Balance = "$15,786.90",
                            Date = "2019-12-05",
                            Description = "DIRECT DEPOSIT - PAYROLL",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Amount = 200.00m,
                            Balance = "$15,586.90",
                            Date = "2019-12-05",
                            Description = "ATM WITHDRAWAL - MAIN ST BRANCH",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 89.99m,
                            Balance = "$15,496.91",
                            Date = "2019-12-06",
                            Description = "AMAZON.COM PURCHASE ORDER #112-3948571",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 6.75m,
                            Balance = "$15,490.16",
                            Date = "2019-12-06",
                            Description = "STARBUCKS #00384 COFFEE PURCHASE",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 145.23m,
                            Balance = "$15,344.93",
                            Date = "2019-12-07",
                            Description = "UTILITY BILL PAYMENT - GAS & ELECTRIC",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 22.50m,
                            Balance = "$15,367.43",
                            Date = "2019-12-07",
                            Description = "INTEREST CREDIT - SAVINGS BONUS",
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
